<?php
$default_value = 1;

return [
    'Roma'=>$default_value,
    'Milano'=>$default_value,
    'Napoli'=>$default_value,
    'Torino'=>$default_value,
    'Palermo'=>$default_value,
    'Genova'=>$default_value,
    'Bologna'=>$default_value,
    'Firenze'=>$default_value,
    'Bari'=>$default_value,
    'Catania'=>$default_value,
    'Venezia'=>$default_value,
    'Verona'=>$default_value,
    'Messina'=>$default_value,
    'Padova'=>$default_value,
    'Trieste'=>$default_value,
    'Brescia'=>$default_value,
    'Parma'=>$default_value,
    'Taranto'=>$default_value,
    'Prato'=>$default_value,
    'Modena'=>$default_value,
    'Reggio Calabria'=>$default_value,
    'Livorno'=>$default_value,
    'Cagliari'=>$default_value,
    'Perugia'=>$default_value,
    'Salerno'=>$default_value,
    'Ravenna'=>$default_value,
    'Ferrara'=>$default_value,
    'Rimini'=>$default_value,
    'Sassari'=>$default_value,
    'Lecce'=>$default_value,
];